# Filtering and Ordering in Pandas

In [2]:
# Importing library for panda
import pandas as pd

In [4]:
# Loading csv file using pandas
df = pd.read_csv('world_population.csv')
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

## Filtering By Columns

In [5]:
# Filtering
# We are displaying only those rows where rank is below or equal to 5
df[df['Rank'] <= 5]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

In [6]:
# Filtering
# We are displaying only the rows where continent is North America
df[df['Continent'] == 'North America']

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
6,224,AIA,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint John’s,North America,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
10,198,ABW,Aruba,Oranjestad,North America,106445.0,106585.0,104257.0,100341.0,89101.0,65712.0,62267.0,59106.0,180.0,591.3611,0.9991,0.00
14,176,BHS,Bahamas,Nassau,North America,409984.0,406471.0,392697.0,373272.0,325014.0,270679.0,223752.0,179129.0,13943.0,29.4043,1.0051,0.01
17,186,BRB,Barbados,Bridgetown,North America,281635.0,280693.0,278083.0,274711.0,264657.0,258868.0,253575.0,241397.0,430.0,654.9651,1.0015,0.00
20,177,BLZ,Belize,Belmopan,North America,405272.0,394921.0,359871.0,322106.0,240406.0,182589.0,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
22,206,BMU,Bermuda,Hamilton,North America,64184.0,64031.0,63144.0,63447.0,61371.0,57470.0,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
28,221,VGB,British Virgin Islands,Road Town,North America,31305.0,30910.0,29366.0,27556.0,20104.0,15617.0,11109.0,9581.0,151.0,207.3179,1.0059,0.00
35,39,CAN,Canada,Ottawa,North America,38454327.0,37888705.0,35732126.0,33963412.0,30683313.0,27657204.0,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
37,205,CYM,Cayman Islands,George Town,North America,68706.0,67311.0,60911.0,54074.0,39658.0,26027.0,17100.0,10533.0,264.0,260.2500,1.0084,0.00
45,124,CRI,Costa Rica,San José,North America,5180829.0,5123105.0,4895242.0,4622252.0,3979193.0,3158253.0,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
47,85,CUB,Cuba,Havana,North America,11212191.0,11300698.0,11339894.0,11290417.0,11105791.0,10626680.0,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14
48,189,CUW,Curacao,Willemstad,North America,191163.0,189288.0,169572.0,159380.0,141424.0,155446.0,156851.0,150385.0,444.0,430.5473,1.0043,0.00
53,204,DMA,Dominica,Roseau,North America,72737.0,71995.0,70007.0,68755.0,68346.0,69481.0,72978.0,68895.0,751.0,96.8535,1.0045,0.00
54,84,DOM,Dominican Republic,Santo Domingo,North America,11228821.0,10999664.0,10405832.0,9775755.0,8540791.0,7129004.0,5755800.0,4475871.0,48671.0,230.7087,1.0100,0.14
58,112,SLV,El Salvador,San Salvador,North America,6336392.0,6292731.0,6231066.0,6114034.0,5958482.0,5367179.0,4508992.0,3619090.0,21041.0,301.1450,1.0035,0.08
78,208,GRL,Greenland,Nuuk,North America,56466.0,56026.0,55895.0,56351.0,56184.0,55599.0,50106.0,45434.0,2166086.0,0.0261,1.0040,0.00
79,193,GRD,Grenada,Saint George's,North America,125438.0,123663.0,118980.0,114039.0,107432.0,99047.0,94838.0,98794.0,344.0,364.6453,1.0066,0.00
80,178,GLP,Guadeloupe,Basse-Terre,North America,395752.0,395642.0,399089.0,403072.0,424067.0,391951.0,334234.0,318310.0,1628.0,243.0909,0.9992,0.00
82,68,GTM,Guatemala,Guatemala City,North America,17843908.0,17362718.0,16001107.0,14543121.0,11735894.0,9084780.0,6987767.0,5453208.0,108889.0,163.8725,1.0134,0.22
87,82,HTI,Haiti,Port-au-Prince,North America,11584996.0,11306801.0,10563757.0,9842880.0,8360225.0,6925331.0,5646676.0,4680812.0,27750.0,417.4773,1.0120,0.15
88,89,HND,Honduras,Tegucigalpa,North America,10432860.0,10121763.0,9294505.0,8450933.0,6656725.0,5053234.0,3777990.0,2782753.0,112492.0,92.7431,1.0150,0.13
101,139,JAM,Jamaica,Kingston,North America,2827377.0,2820436.0,2794445.0,2733896.0,2612205.0,2392030.0,2135546.0,1859091.0,10991.0,NaN,NaN,0.04
127,180,MTQ,Martinique,Fort-de-France,North America,367507.0,370391.0,383515.0,392181.0,432543.0,374271.0,333786.0,326428.0,1128.0,325.8041,0.9965,0.00
131,10,MEX,Mexico,Mexico City,North America,127504125.0,125998302.0,120149897.0,112532401.0,97873442.0,81720428.0,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
137,230,MSR,Montserrat,Brades,North America,4390.0,4500.0,5059.0,4938.0,5138.0,10805.0,11452.0,11402.0,102.0,43.0392,0.9939,0.00
147,106,NIC,Nicaragua,Managua,North America,6948392.0,6755895.0,6298598.0,5855734.0,5123222.0,4227820.0,3303309.0,2444767.0,130373.0,53.2962,1.0143,0.09
159,128,PAN,Panama,Panama City,North America,4408581.0,4294396.0,3957099.0,3623617.0,3001731.0,2449968.0,1956987.0,1516188.0,75417.0,58.4561,1.0132,0.06
166,136,PRI,Puerto Rico,San Juan,North America,3252407.0,3271564.0,3497335.0,3717922.0,3827108.0,3543776.0,3214568.0,2737619.0,8870.0,366.6750,0.9989,0.04
173,228,BLM,Saint Barthelemy,Gustavia,North America,10967.0,10681.0,9643.0,8988.0,7082.0,5168.0,2983.0,2417.0,21.0,522.2381,1.0098,0.00
174,211,KNA,Saint Kitts and Nevis,Basseterre,North America,47657.0,47642.0,47790.0,47403.0,45461.0,40636.0,43097.0,44968.0,261.0,182.5939,1.0011,0.00
175,190,LCA,Saint Lucia,Castries,North America,179857.0,179237.0,175623.0,170935.0,159500.0,142301.0,121633.0,103090.0,616.0,291.9756,1.0011,0.00
176,220,MAF,Saint Martin,Marigot,North America,31791.0,32552.0,35020.0,36458.0,29610.0,28127.0,7776.0,5802.0,53.0,599.8302,0.9951,0.00
177,229,SPM,Saint Pierre and Miquelon,Saint-Pierre,North America,5862.0,5906.0,5978.0,6052.0,6274.0,6324.0,6106.0,5537.0,242.0,24.2231,0.9964,0.00
178,199,VCT,Saint Vincent and the Grenadines,Kingstown,North America,103948.0,104632.0,106482.0,109308.0,113813.0,112487.0,107480.0,98459.0,389.0,267.2185,0.9963,0.00
188,214,SXM,Sint Maarten,Philipsburg,North America,44175.0,43621.0,40205.0,33034.0,30489.0,27845.0,12243.0,6260.0,34.0,1299.2647,1.0030,0.00
211,153,TTO,Trinidad and Tobago,Port-of-Spain,North America,1531044.0,1518147.0,1460177.0,1410296.0,1332203.0,1266518.0,1127852.0,988890.0,5130.0,NaN,1.0035,0.02
215,212,TCA,Turks and Caicos Islands,Cockburn Town,North America,45703.0,44276.0,36538.0,29726.0,18744.0,11709.0,7598.0,5665.0,948.0,48.2099,1.0131,0.00
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [7]:
# If you want to add two conditions
# Displaying rows where country is china and india
df[(df['Country'] == 'China') | (df['Country'] == 'India')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77

In [8]:
# Both these give same output
specific = ['China', 'India']
df[df['Country'].isin(specific)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77

In [14]:
# This also gives the same output as other two
df[df['Country'].str.contains('China|India', na=False)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77

## Filtering By Index

In [16]:
# Now we are makiing one of our column (country) as index
df1 = df.set_index('Country')
df1

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [18]:
# Getting the only required columns
df1.filter(items = ['Continent', 'CCA3', 'Rank'], axis = 1)

                  Continent CCA3  Rank
Country
Afghanistan            Asia  AFG    36
Albania              Europe  ALB   138
Algeria              Africa  DZA    34
American Samoa      Oceania  ASM   213
Andorra              Europe  AND   203
...                     ...  ...   ...
Wallis and Futuna   Oceania  WLF   226
Western Sahara       Africa  ESH   172
Yemen                  Asia  YEM    46
Zambia               Africa  ZMB    63
Zimbabwe             Africa  ZWE    74

[234 rows x 3 columns]

In [20]:
# DSo this wa we can filter out all the information specifically for yemen country
df1.filter(items = ['Yemen'], axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42

In [22]:
# Can also do this if we want it for more countries
df1.filter(like = 'United', axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

#### loc and iloc

In [23]:
# Since we have made country as index, we ccan now get all columns data of any country using loc
df1.loc['Yemen']

Rank                                   46
CCA3                                  YEM
Capital                             Sanaa
Continent                            Asia
2022 Population                33696614.0
2020 Population                32284046.0
2015 Population                28516545.0
2010 Population                24743946.0
2000 Population                18628700.0
1990 Population                13375121.0
1980 Population                 9204938.0
1970 Population                 6843607.0
Area (km²)                       527968.0
Density (per km²)                 63.8232
Growth Rate                        1.0217
World Population Percentage          0.42
Name: Yemen, dtype: object

In [24]:
# Getting all the columns data for United States
df1.loc['United States']

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

In [25]:
# This will check and give all the columns data for index 3 excluding the country
df1.iloc[3]

Rank                                 213
CCA3                                 ASM
Capital                        Pago Pago
Continent                        Oceania
2022 Population                  44273.0
2020 Population                  46189.0
2015 Population                  51368.0
2010 Population                  54849.0
2000 Population                  58230.0
1990 Population                  47818.0
1980 Population                  32886.0
1970 Population                  27075.0
Area (km²)                         199.0
Density (per km²)               222.4774
Growth Rate                       0.9831
World Population Percentage          0.0
Name: American Samoa, dtype: object

## Ordering

In [26]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [30]:
# All the rows where rank is less than equal to 10
# Orderinng it by rank, in ascending order
df[df['Rank'] <= 10].sort_values(by='Rank')

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60

In [31]:
# All the rows where rank is less than equal to 10
# Orderinng it by rank, in ascending order
df[df['Rank'] <= 10].sort_values(by='Rank', ascending = False)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88

In [36]:
# You can add 2 thing or more in order by
# However it follows the order of the first provided column and ignores the second one
# asecending = true gives ascending order and false gives descending order
df[df['Rank'] <= 10].sort_values(by=['Continent', 'Rank'], ascending = False)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74